### ISSUE TITLE
com.zaxxer.hikari.HikariConfig - The initializationFailFast propery is deprecated

### ISSUE THREAD

**Issue by ghisvail** [slicebox/slicebox#277]
I am getting the following warning in the logs:
```
2018-04-23 13:21:28,436 WARN  com.zaxxer.hikari.HikariConfig - The initializationFailFast propery is deprecated, see initializationFailTimeout
```

**Comment by KarlSjostrand** [comment]
I think this is because we are specifying a later version of HikariCP than used internally by Slick. See https://github.com/slick/slick/blob/56cc13e97c90b4a86bee36c3febc2fc2667cc9a3/project/Build.scala#L35 for version used by Slick and https://github.com/slick/slick/blob/56cc13e97c90b4a86bee36c3febc2fc2667cc9a3/project/Build.scala#L35 for version used by us. Should we downgrade?

**Comment by ghisvail** [comment]
Since you are not using `HikariCP` directly, it might be worth leaving it in sync with the version in `Slick`?

**Comment by KarlSjostrand** [comment]
You mean not depending explicitly on Hikari at all and let Slick determine the version? That might be a good idea, it is not marked as "provided" i Slick as far as I can see.
